package com.akshay.CareerNest.entity;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "applications")
public class Application {

    @Id
    private String id;    // Auto-generated by Mongo

    private String jobId;         // The Job this application is linked to
    private String name;
    private String email;
    private String phone;
    private String education;
    private String skills;
    private String resumePath;    // Local file path where resume is stored
}
